# Generated by Django 6.0.5 on 2026-05-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intents_api', '0004_task_subtasks_alter_activitylog_id_alter_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='study_guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
